# Enable true color
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:Tc"

# Enable mouse support
set -g mouse on

# Unbind the default prefix
unbind C-b
set -g prefix C-,
bind C-, send-prefix

# Vim style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at index 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Switch between windows with Ctrl+q (previous window) and Ctrl+w (next window)
bind-key -n C-q previous-window
bind-key -n C-w next-window

# Bindings to swap the current window with the previous or next window
bind < swap-window -t -1
bind > swap-window -t +1

# Set catppuccin flavor
set -g @catppuccin_flavour 'mocha'

# Plugin configurations
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize tmux plugin manager
run '~/.config/tmux/plugins/tpm/tpm'

## catppuccin
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_modules_right "directory date_time session"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
set -g @catppuccin_window_current_text "#W"

# Enable vi-mode for copy mode
set-window-option -g mode-keys vi
bind , send-prefix \; copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Splitting windows
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

# Bind new resize keybindings
bind -n C-S-h resize-pane -L 4 
bind -n C-S-l resize-pane -R 4 
bind -n C-S-k resize-pane -U 4 
bind -n C-S-j resize-pane -D 4 

# Store previous width and height for panes
set -g @right_pane_prev_width 0
set -g @bottom_pane_prev_height 0
set -g @left_pane_prev_width 0

# Toggle logs pane (pane 4)
bind-key l run-shell '
PANE_ID=4;
CURRENT_WIDTH=$(~/get_pane_size.sh $PANE_ID width);
if [ "$CURRENT_WIDTH" -eq 1 ]; then
  PREV_WIDTH=$(tmux show-option -gqv @right_pane_prev_width);
  if [ -z "$PREV_WIDTH" ] || [ "$PREV_WIDTH" -eq 1 ]; then
    PREV_WIDTH=$(($(tmux display -p "#{window_width}") * 1 / 5));
  fi
  tmux resize-pane -t 4 -x $PREV_WIDTH;
else
  if [ "$CURRENT_WIDTH" -gt 1 ]; then
    tmux set-option -g @right_pane_prev_width $CURRENT_WIDTH;
  fi
  tmux resize-pane -t 4 -x 1;
fi
'

# Toggle command pane (pane 3)
bind-key j run-shell '
PANE_ID=3;
CURRENT_HEIGHT=$(~/get_pane_size.sh $PANE_ID height);
if [ "$CURRENT_HEIGHT" -eq 1 ]; then
  PREV_HEIGHT=$(tmux show-option -gqv @bottom_pane_prev_height);
  if [ -z "$PREV_HEIGHT" ] || [ "$PREV_HEIGHT" -eq 1 ]; then
    PREV_HEIGHT=$(($(tmux display -p "#{window_height}") * 1 / 5));
  fi
  tmux resize-pane -t 3 -y $PREV_HEIGHT;
else
  if [ "$CURRENT_HEIGHT" -gt 1 ]; then
    tmux set-option -g @bottom_pane_prev_height $CURRENT_HEIGHT;
  fi
  tmux resize-pane -t 3 -y 1;
fi
'

# Toggle documentation pane (pane 1)
bind-key h run-shell '
PANE_ID=1;
CURRENT_WIDTH=$(~/get_pane_size.sh $PANE_ID width);
if [ "$CURRENT_WIDTH" -eq 1 ]; then
  PREV_WIDTH=$(tmux show-option -gqv @left_pane_prev_width);
  if [ -z "$PREV_WIDTH" ] || [ "$PREV_WIDTH" -eq 1 ]; then
    PREV_WIDTH=$(($(tmux display -p "#{window_width}") * 1 / 5));
  fi
  tmux resize-pane -t 1 -x $PREV_WIDTH;
else
  if [ "$CURRENT_WIDTH" -gt 1 ]; then
    tmux set-option -g @left_pane_prev_width $CURRENT_WIDTH;
  fi
  tmux resize-pane -t 1 -x 1;
fi
'
