# docker-compose
# docker-compose logs
#(^|[/\w\.]+/)docker-compose logs\s
^([/\w\.]+\/)?docker-compose logs\b
conf.golang
^([/\w\.]+\/)?docker compose logs\b
conf.golang
^([/\w\.]+\/)?jq\b
conf.golang
